"""GENERATED by tools/regenerate_currency_data.py — do not edit by hand.

English currency word recognition keys (grammar data).

Source: keys of NAME_TO_CODES in paxman/capabilities/Money/rules/data/
cldr_currencies.py (Unicode CLDR v47 English display names).

Keys are Title-Case (D4 divergence: Currency folds to lowercase and
stores lowercase keys; Money keeps Title-Case and does case-
insensitive lookup via _NAME_TO_CODES_LOWER in
cldr_currencies_ed2025.py — WordRecognition is case-insensitive
(re.IGNORECASE) and preserves as-written, so the rule normalizes
via the lower fallback map).

Ordered longest-first so the grammar alternates multi-word names
before their shorter tails when present.
"""

from __future__ import annotations

WORD_TOKENS: tuple[str, ...] = (
    "Boliviano",
    "Lilangeni",
    "Afghani",
    "Bolivar",
    "Cordoba",
    "Guarani",
    "Hryvnia",
    "Lempira",
    "Quetzal",
    "Ringgit",
    "Rufiyaa",
    "Dirham",
    "Dollar",
    "Florin",
    "Forint",
    "Koruna",
    "Kwacha",
    "Pataca",
    "Rupiah",
    "Shekel",
    "Somoni",
    "Tugrik",
    "Colon",
    "Dinar",
    "Franc",
    "Krona",
    "Krone",
    "Manat",
    "Naira",
    "Nakfa",
    "Pound",
    "Riyal",
    "Ruble",
    "Rupee",
    "Tenge",
    "Zloty",
    "Baht",
    "Cedi",
    "Dong",
    "Dram",
    "Euro",
    "Kina",
    "Kyat",
    "Lari",
    "Lira",
    "Mark",
    "Peso",
    "Pula",
    "Rand",
    "Real",
    "Rial",
    "Riel",
    "Taka",
    "Tala",
    "Vatu",
    "Yuan",
    "Kip",
    "Leu",
    "Sol",
    "Som",
    "Won",
    "Yen",
)
