"""GENERATED by tools/regenerate_unicode_property_data.py — do not edit by hand.

Source: https://unicode.org/Public/15.1.0/ucd/PropList.txt and Scripts.txt
Unicode version: 15.1.0
"""

from __future__ import annotations

UNICODE_VERSION: str = "15.1.0"
SOURCE_URL: str = "https://unicode.org/Public/15.1.0/ucd/PropList.txt and Scripts.txt"

SC_RANGES: tuple[tuple[int, int], ...] = (
    (0x0024, 0x0024),
    (0x00A2, 0x00A5),
    (0x0594, 0x0594),
    (0x060B, 0x060B),
    (0x09F2, 0x09F3),
    (0x09F4, 0x09F4),
    (0x09F9, 0x09F9),
    (0x207A, 0x207A),
    (0x20A8, 0x20BF),
    (0xA838, 0xA838),
)

HAN_RANGES: tuple[tuple[int, int], ...] = (
    (0x3400, 0x4DBF),
    (0x4E00, 0x9FFF),
    (0x20000, 0x2A6D6),
    (0x2A700, 0x2B734),
    (0x2B740, 0x2B81D),
)
