"""GENERATED by tools/regenerate_unicode_property_data.py — do not edit by hand.

Unicode property ranges — generated sorted-range tuples (ICU discipline).

Source: https://unicode.org/Public/15.1.0/ucd/PropList.txt
Version: Unicode 15.1.0
SHA: ca3e3a097e8e

Generated from paxman/shared_data/unicode_property_snapshot.json
 — do not edit by hand.
Regenerate with: uv run python tools/regenerate_unicode_property_data.py
"""

from __future__ import annotations

UNICODE_RANGES: tuple[tuple[int, int], ...] = ()
