"""GENERATED by tools/regenerate_iban_registry_data.py — do not edit by hand.

IBAN registry — SWIFT 90-country rows (stub).

Source: https://www.swift.com/standards/data-standards/iban-registry
Version: SWIFT R100
SHA: 7b66ae662433

Generated from paxman/shared_data/iban_registry_snapshot.json
 — do not edit by hand.
Regenerate with: uv run python tools/regenerate_iban_registry_data.py
"""

from __future__ import annotations

REGISTRY: dict[str, object] = {}
