"""GENERATED by tools/regenerate_language_data.py — do not edit by hand.

English language name recognition keys (grammar data).

Source: ISO 639 English Description + IANA Registry
Reference: https://www.iso.org/standard/22109.html
Keys are normalize_name() output (lower, accent-stripped, space-collapsed).

Completeness: curatorial subset (60 entries from snapshot). The full
IANA Language Subtag Registry Description set (7,900+) and CLDR root
are not yet materialized. Names outside this subset are MISSING
(grammar emits no match), not INVALID — no false negative under the
current completeness contract. Full IANA Description coverage is
tracked as follow-up work; snapshot _meta documents provenance.

Generated from paxman/shared_data/language_snapshot.json — do not edit by hand.
Regenerate with: uv run python tools/regenerate_language_data.py
"""

from __future__ import annotations

ENGLISH_LANGUAGE_KEYS: frozenset[str] = frozenset(
    {
        "afrikaans",
        "albanian",
        "amharic",
        "arabic",
        "armenian",
        "azerbaijani",
        "basque",
        "belarusian",
        "bengali",
        "bihari",
        "bulgarian",
        "catalan",
        "cherokee",
        "chinese",
        "croatian",
        "czech",
        "danish",
        "dutch",
        "english",
        "estonian",
        "finnish",
        "french",
        "georgian",
        "german",
        "greek",
        "gujarati",
        "hebrew",
        "hindi",
        "icelandic",
        "indonesian",
        "irish",
        "italian",
        "japanese",
        "korean",
        "macedonian",
        "malay",
        "maltese",
        "moldavian",
        "moldovan",
        "norwegian",
        "norwegian bokmal",
        "persian",
        "polish",
        "portuguese",
        "romanian",
        "russian",
        "serbian",
        "serbo croatian",
        "slovak",
        "slovenian",
        "spanish",
        "swahili",
        "swedish",
        "thai",
        "turkish",
        "ukrainian",
        "urdu",
        "vietnamese",
        "welsh",
        "yiddish",
    }
)
