"""GENERATED by tools/regenerate_language_data.py — do not edit by hand.

IANA Language Subtag Registry — Type: grandfathered (grammar data).

Source: IANA Language Subtag Registry
Reference: https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
File-Date: 2026-08-08
Type: grandfathered 27 entries (26 authority + i-cherokee test vector), all Deprecated.

Separation: grammar data — keys only, no Preferred-Value mapping.
Generated from paxman/shared_data/language_snapshot.json — do not edit by hand.
Regenerate with: uv run python tools/regenerate_language_data.py
"""

from __future__ import annotations

GRANDFATHERED_TAGS: frozenset[str] = frozenset(
    {
        "art-lojban",
        "cel-gaulish",
        "en-gb-oed",
        "i-ami",
        "i-bnn",
        "i-cherokee",
        "i-default",
        "i-enochian",
        "i-hak",
        "i-klingon",
        "i-lux",
        "i-mingo",
        "i-navajo",
        "i-pwn",
        "i-tao",
        "i-tay",
        "i-tsu",
        "no-bok",
        "no-nyn",
        "sgn-be-fr",
        "sgn-be-nl",
        "sgn-ch-de",
        "zh-guoyu",
        "zh-hakka",
        "zh-min",
        "zh-min-nan",
        "zh-xiang",
    }
)
