"""GENERATED by tools/regenerate_iana_language_data.py — do not edit by hand.

IANA language subtag registry — stub (full registry ~8k entries).

Source: https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
Version: 2026-08-08
SHA: b6d8f4215b6b

Generated from paxman/shared_data/iana_language_snapshot.json
 — do not edit by hand.
Regenerate with: uv run python tools/regenerate_iana_language_data.py
"""

from __future__ import annotations

IANA_REGISTRY: dict[str, object] = {}
