"""GENERATED by tools/regenerate_language_data.py — do not edit by hand.

Localized (CLDR) language name recognition keys (grammar data).

Source: CLDR language display names (subset: en/fr/de/es latn)
Reference: https://www.unicode.org/cldr/charts/46/summary/root.html
Keys are normalize_name() output (lower, accent-stripped, space-collapsed).

Completeness: curatorial subset (24 entries from snapshot). Full
CLDR v46 locale coverage is not yet generated. In-subset localized
names without include_localized are INVALID (grammar recognizes,
engine drops the CLDR rule via requires_features); out-of-subset
names are MISSING (grammar emits no match), not INVALID. Snapshot
_meta documents unsupported provenance.

Generated from paxman/shared_data/language_snapshot.json — do not edit by hand.
Regenerate with: uv run python tools/regenerate_language_data.py
"""

from __future__ import annotations

LOCALIZED_LANGUAGE_KEYS: frozenset[str] = frozenset(
    {
        "allemand",
        "anglais",
        "arabic",
        "cesky",
        "chinese",
        "chino",
        "dansk",
        "deutsch",
        "espanol",
        "francais",
        "greek",
        "hebrew",
        "italiano",
        "japanese",
        "japones",
        "korean",
        "magyar",
        "nederlands",
        "norsk",
        "polski",
        "portugues",
        "russian",
        "suomi",
        "svenska",
    }
)
