"""GENERATED by tools/regenerate_iana_language_data.py — do not edit by hand.

Language name recognition keys — derived projection from
CLDR/ISO 639 language display names (grammar data, keys only).

Source: https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
Version: 2026-08-08
SHA: 84413739b42c

Grammar data — keys only, no canonical mapping. Rule data in
paxman/capabilities/Language/rules/data/english_language_map.py
is the single source of truth; this module is a generated
projection (F8 / D10).
Generated from paxman/shared_data/language_snapshot.json
 — do not edit by hand.
Regenerate with: uv run python tools/regenerate_iana_language_data.py
"""

from __future__ import annotations

NAME_TOKENS: frozenset[str] = frozenset(
    {
        "afrikaans",
        "albanian",
        "allemand",
        "amharic",
        "anglais",
        "arabic",
        "armenian",
        "azerbaijani",
        "basque",
        "belarusian",
        "bengali",
        "bihari",
        "bulgarian",
        "catalan",
        "cesky",
        "cherokee",
        "chinese",
        "chino",
        "croatian",
        "czech",
        "danish",
        "dansk",
        "deutsch",
        "dutch",
        "english",
        "espanol",
        "estonian",
        "finnish",
        "francais",
        "french",
        "georgian",
        "german",
        "greek",
        "gujarati",
        "hebrew",
        "hindi",
        "icelandic",
        "indonesian",
        "irish",
        "italian",
        "italiano",
        "japanese",
        "japones",
        "korean",
        "macedonian",
        "magyar",
        "malay",
        "maltese",
        "moldavian",
        "moldovan",
        "nederlands",
        "norsk",
        "norwegian",
        "norwegian bokmal",
        "persian",
        "polish",
        "polski",
        "portugues",
        "portuguese",
        "romanian",
        "russian",
        "serbian",
        "serbo croatian",
        "slovak",
        "slovenian",
        "spanish",
        "suomi",
        "svenska",
        "swahili",
        "swedish",
        "synthetic language 000",
        "synthetic language 001",
        "synthetic language 002",
        "synthetic language 003",
        "synthetic language 004",
        "synthetic language 005",
        "synthetic language 006",
        "synthetic language 007",
        "synthetic language 008",
        "synthetic language 009",
        "synthetic language 010",
        "synthetic language 011",
        "synthetic language 012",
        "synthetic language 013",
        "synthetic language 014",
        "synthetic language 015",
        "synthetic language 016",
        "synthetic language 017",
        "synthetic language 018",
        "synthetic language 019",
        "synthetic language 020",
        "synthetic language 021",
        "synthetic language 022",
        "thai",
        "turkish",
        "ukrainian",
        "urdu",
        "vietnamese",
        "welsh",
        "yiddish",
    }
)
