"""GENERATED by tools/regenerate_currency_data.py — do not edit by hand.

Currency symbol recognition keys (grammar data).

Source: keys of SYMBOL_TO_CODES in paxman/capabilities/Currency/rules/data/
cldr_currencies.py (Unicode CLDR v47, en + es).

Qualified symbols (containing an ASCII letter, e.g. US$, CA$, RM)
are ordered longest-first, qualified-first within equal length
via LexiconAlternation (so the grammar alternates "US$" before
"$" and "Kz" before "K"). The file's pre-sort is
qualified-first longest-first; runtime LexiconStage re-sorts by
(-len, -is_qualified), so the effective alternation is
longest-first. Both guarantee prefix safety.
"""

from __future__ import annotations

SYMBOL_TOKENS: tuple[str, ...] = (
    "CFPF",
    "FCFA",
    "CA$",
    "CN¥",
    "Cg.",
    "EC$",
    "GH₵",
    "HK$",
    "MX$",
    "NT$",
    "NZ$",
    "US$",
    "lei",
    "A$",
    "Ar",
    "Bs",
    "C$",
    "CF",
    "Db",
    "E£",
    "FG",
    "Ft",
    "KM",
    "Kz",
    "Kč",
    "L£",
    "R$",
    "RF",
    "RM",
    "Rp",
    "Rs",
    "T$",
    "ZK",
    "kr",
    "zł",
    "K",
    "L",
    "P",
    "Q",
    "R",
    "р.",
    "$",
    "£",
    "¥",
    "֏",
    "؋",
    "৳",
    "฿",
    "៛",
    "₡",
    "₦",
    "₩",
    "₪",
    "₫",
    "€",
    "₭",
    "₮",
    "₱",
    "₲",
    "₴",
    "₸",
    "₹",
    "₺",
    "₼",
    "₽",
    "₾",
    "⃀",
)
