"""GENERATED by tools/regenerate_language_data.py — do not edit by hand.

Language display name → canonical code mappings.

Source: ISO 639 English Description + IANA Registry
Reference: https://www.iso.org/standard/22109.html
CLDR Source: https://www.unicode.org/cldr/charts/46/summary/root.html

Keys are normalize_name() output (lower, accent-stripped, space-collapsed).
Values are lower canonical language codes (alpha-2 when available, else alpha-3 Term).

Completeness: English names are a curatorial subset (60 entries);
localized names are a CLDR subset (24 entries, en/fr/de/es). The
full IANA Registry Description set (7,900+) and CLDR v46 root locale
are not yet materialized. Names outside these subsets are MISSING
(grammar emits no match) rather than INVALID, avoiding false
negatives under the current completeness contract. Full coverage
will be generated from the IANA Registry file and CLDR root data;
until then unsupported provenance is documented in the snapshot
_meta and capability docstring.

Separation: authority-backed tables serving rules only.
Generated from paxman/shared_data/language_snapshot.json — do not edit by hand.
Regenerate with: uv run python tools/regenerate_language_data.py
"""

from __future__ import annotations

NAME_TO_CANONICAL: dict[str, str] = {
    "afrikaans": "af",
    "albanian": "sq",
    "amharic": "am",
    "arabic": "ar",
    "armenian": "hy",
    "azerbaijani": "az",
    "basque": "eu",
    "belarusian": "be",
    "bengali": "bn",
    "bihari": "bih",
    "bulgarian": "bg",
    "catalan": "ca",
    "cherokee": "chr",
    "chinese": "zh",
    "croatian": "hr",
    "czech": "cs",
    "danish": "da",
    "dutch": "nl",
    "english": "en",
    "estonian": "et",
    "finnish": "fi",
    "french": "fr",
    "georgian": "ka",
    "german": "de",
    "greek": "el",
    "gujarati": "gu",
    "hebrew": "he",
    "hindi": "hi",
    "icelandic": "is",
    "indonesian": "id",
    "irish": "ga",
    "italian": "it",
    "japanese": "ja",
    "korean": "ko",
    "macedonian": "mk",
    "malay": "ms",
    "maltese": "mt",
    "moldavian": "ro",
    "moldovan": "ro",
    "norwegian": "no",
    "norwegian bokmal": "nb",
    "persian": "fa",
    "polish": "pl",
    "portuguese": "pt",
    "romanian": "ro",
    "russian": "ru",
    "serbian": "sr",
    "serbo croatian": "sh",
    "slovak": "sk",
    "slovenian": "sl",
    "spanish": "es",
    "swahili": "sw",
    "swedish": "sv",
    "thai": "th",
    "turkish": "tr",
    "ukrainian": "uk",
    "urdu": "ur",
    "vietnamese": "vi",
    "welsh": "cy",
    "yiddish": "yi",
}

LOCALIZED_NAME_TO_CANONICAL: dict[str, str] = {
    "allemand": "de",
    "anglais": "en",
    "arabic": "ar",
    "cesky": "cs",
    "chinese": "zh",
    "chino": "zh",
    "dansk": "da",
    "deutsch": "de",
    "espanol": "es",
    "francais": "fr",
    "greek": "el",
    "hebrew": "he",
    "italiano": "it",
    "japanese": "ja",
    "japones": "ja",
    "korean": "ko",
    "magyar": "hu",
    "nederlands": "nl",
    "norsk": "no",
    "polski": "pl",
    "portugues": "pt",
    "russian": "ru",
    "suomi": "fi",
    "svenska": "sv",
}

CLDR_MAP: dict[str, str] = LOCALIZED_NAME_TO_CANONICAL
