"""Regenerate Currency + Money data modules from shared snapshot.

Source: paxman/shared_data/currency_snapshot.json (CLDR v47 + ISO 4217).
Outputs (8 files, deterministic, longest-first ordering for tokens):
- paxman/capabilities/Currency/grammar/data/currency_symbols.py
- paxman/capabilities/Currency/grammar/data/currency_words.py
- paxman/capabilities/Currency/rules/data/cldr_currencies.py
- paxman/capabilities/Currency/rules/data/iso4217_list_one.py
- paxman/capabilities/Money/grammar/data/currency_symbols.py
- paxman/capabilities/Money/grammar/data/currency_words.py
- paxman/capabilities/Money/rules/data/cldr_currencies.py
- paxman/capabilities/Money/rules/data/iso4217_list_one.py

Regeneration preserves import-linter isolation: each capability gets its own
local table; sibling imports remain banned (M8).

Usage:
    uv run python tools/regenerate_currency_data.py
    uv run python tools/regenerate_currency_data.py --check
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, cast

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / "paxman" / "shared_data" / "currency_snapshot.json"

_GENERATED_HEADER = (
    "GENERATED by tools/regenerate_currency_data.py — do not edit by hand."
)

OUTPUTS = [
    ROOT
    / "paxman"
    / "capabilities"
    / "Currency"
    / "grammar"
    / "data"
    / "currency_symbols.py",
    ROOT
    / "paxman"
    / "capabilities"
    / "Currency"
    / "grammar"
    / "data"
    / "currency_words.py",
    ROOT
    / "paxman"
    / "capabilities"
    / "Currency"
    / "rules"
    / "data"
    / "cldr_currencies.py",
    ROOT
    / "paxman"
    / "capabilities"
    / "Currency"
    / "rules"
    / "data"
    / "iso4217_list_one.py",
    ROOT
    / "paxman"
    / "capabilities"
    / "Money"
    / "grammar"
    / "data"
    / "currency_symbols.py",
    ROOT
    / "paxman"
    / "capabilities"
    / "Money"
    / "grammar"
    / "data"
    / "currency_words.py",
    ROOT
    / "paxman"
    / "capabilities"
    / "Money"
    / "rules"
    / "data"
    / "cldr_currencies.py",
    ROOT
    / "paxman"
    / "capabilities"
    / "Money"
    / "rules"
    / "data"
    / "iso4217_list_one.py",
]


def _emit_module(docstring: str, assignment: str) -> str:
    return (
        '"""'
        + _GENERATED_HEADER
        + "\n\n"
        + docstring
        + '"""\n\nfrom __future__ import annotations\n\n'
        + assignment
        + "\n"
    )


def _load_snapshot() -> dict[str, Any]:
    return cast(dict[str, Any], json.loads(SNAPSHOT.read_text(encoding="utf-8")))


def _as_dict(value: Any) -> dict[str, Any]:
    if isinstance(value, dict):
        return cast(dict[str, Any], value)
    return {}


def _as_list(value: Any) -> list[Any]:
    if isinstance(value, list):
        return cast(list[Any], value)
    return []


def _str_list(value: Any) -> list[str]:
    if isinstance(value, list):
        return [str(item) for item in cast(list[Any], value)]
    return []


def _is_qualified(token: str) -> bool:
    return any(ch.isascii() and ch.isalpha() for ch in token)


def _symbol_tokens_sorted(symbols: list[str]) -> tuple[str, ...]:
    def rank(s: str) -> tuple[int, int, str]:
        qualified = 0 if _is_qualified(s) else 1
        return (qualified, -len(s), s)

    return tuple(sorted(symbols, key=rank))


def _word_tokens_sorted(words: list[str]) -> tuple[str, ...]:
    return tuple(sorted(words, key=lambda w: (-len(w), w)))


def _emit_currency_symbols(snapshot: dict[str, Any], *, for_money: bool) -> str:
    # Source: symbol_to_codes keys; qualified-first longest-first.
    raw_symbols = _as_dict(snapshot.get("symbol_to_codes"))
    symbols: list[str] = list(raw_symbols.keys())
    # Fallback to cldr_currencies.symbol_to_codes if top-level missing.
    if not symbols:
        cldr = _as_dict(snapshot.get("cldr_currencies"))
        inner = _as_dict(cldr.get("symbol_to_codes"))
        symbols = list(inner.keys())
    tokens = _symbol_tokens_sorted(symbols)
    items = "".join(f'    "{t}",\n' for t in tokens)
    assignment = "SYMBOL_TOKENS: tuple[str, ...] = (\n" + items + ")"
    if for_money:
        docstring = (
            "Currency symbol recognition keys (grammar data).\n"
            "\n"
            "Source: keys of SYMBOL_TO_CODES in "
            "paxman/capabilities/Money/rules/data/\n"
            "cldr_currencies.py (Unicode CLDR v47, en + es).\n"
            "\n"
            "Qualified symbols (containing an ASCII letter, e.g. US$, CA$, RM) are\n"
            "ordered before bare symbols ($, \\u00a5, \\u20ac), longest first within\n"
            'each class, so the grammar alternates "US$" before "$".\n'
        )
    else:
        docstring = (
            "Currency symbol recognition keys (grammar data).\n"
            "\n"
            "Source: keys of SYMBOL_TO_CODES in "
            "paxman/capabilities/Currency/rules/data/\n"
            "cldr_currencies.py (Unicode CLDR v47, en + es).\n"
            "\n"
            "Qualified symbols (containing an ASCII letter, e.g. US$, CA$, RM)\n"
            "are ordered longest-first, qualified-first within equal length\n"
            'via LexiconAlternation (so the grammar alternates "US$" before\n'
            '"$" and "Kz" before "K"). The file\'s pre-sort is\n'
            "qualified-first longest-first; runtime LexiconStage re-sorts by\n"
            "(-len, -is_qualified), so the effective alternation is\n"
            "longest-first. Both guarantee prefix safety.\n"
        )
    return _emit_module(docstring, assignment)


def _emit_currency_words(snapshot: dict[str, Any], *, for_money: bool) -> str:
    cldr = _as_dict(snapshot.get("cldr_currencies"))
    if for_money:
        name_map = _as_dict(cldr.get("name_to_codes_money"))
        if not name_map:
            name_map = _as_dict(cldr.get("name_to_codes_currency"))
        keys: list[str] = list(name_map.keys())
        tokens = _word_tokens_sorted(keys)
        docstring = (
            "English currency word recognition keys (grammar data).\n"
            "\n"
            "Source: keys of NAME_TO_CODES in "
            "paxman/capabilities/Money/rules/data/\n"
            "cldr_currencies.py (Unicode CLDR v47 English display names).\n"
            "\n"
            "Keys are Title-Case (D4 divergence: Currency folds to lowercase and\n"
            "stores lowercase keys; Money keeps Title-Case and does case-\n"
            "insensitive lookup via _NAME_TO_CODES_LOWER in\n"
            "cldr_currencies_ed2025.py — WordRecognition is case-insensitive\n"
            "(re.IGNORECASE) and preserves as-written, so the rule normalizes\n"
            "via the lower fallback map).\n"
            "\n"
            "Ordered longest-first so the grammar alternates multi-word names\n"
            "before their shorter tails when present.\n"
        )
    else:
        name_map = _as_dict(cldr.get("name_to_codes_currency"))
        keys: list[str] = list(name_map.keys())
        tokens = _word_tokens_sorted(keys)
        docstring = (
            "English currency word recognition keys (grammar data).\n"
            "\n"
            "Source: keys of NAME_TO_CODES in "
            "paxman/capabilities/Currency/rules/data/\n"
            "cldr_currencies.py (Unicode CLDR v47 English display names).\n"
            "\n"
            "Keys are lowercase (D4): the word grammar folds input to lowercase, so\n"
            "the recognition keys match the rule-data lookup keys exactly.\n"
            "\n"
            "Ordered longest-first so the grammar alternates multi-word names\n"
            "before their shorter tails when present.\n"
        )
    items = "".join(f'    "{t}",\n' for t in tokens)
    assignment = "WORD_TOKENS: tuple[str, ...] = (\n" + items + ")"
    return _emit_module(docstring, assignment)


def _format_symbol_to_codes(symbol_to_codes: dict[str, list[str]]) -> str:
    # Deterministic sorted keys; multiline only for the large "$" entry (>10 codes)
    lines: list[str] = []
    lines.append("SYMBOL_TO_CODES: dict[str, tuple[str, ...]] = {")
    for sym in sorted(symbol_to_codes.keys()):
        codes = tuple(symbol_to_codes[sym])
        if len(codes) > 10:
            # multiline for large entry (only "$" currently)
            lines.append(f'    "{sym}": (')
            for code in codes:
                lines.append(f'        "{code}",')
            lines.append("    ),")
        else:
            inner = ", ".join(f'"{c}"' for c in codes)
            # single-value tuples need trailing comma inside
            if len(codes) == 1:
                inner += ","
            lines.append(f'    "{sym}": ({inner}),')
    lines.append("}")
    return "\n".join(lines)


def _format_name_to_codes_sorted(name_to_codes: dict[str, list[str]]) -> str:
    lines: list[str] = []
    lines.append("NAME_TO_CODES: dict[str, tuple[str, ...]] = {")
    for name in sorted(name_to_codes.keys()):
        codes = tuple(name_to_codes[name])
        inner = ", ".join(f'"{c}"' for c in codes)
        if len(codes) == 1:
            inner += ","
        lines.append(f'    "{name}": ({inner}),')
    lines.append("}")
    return "\n".join(lines)


def _emit_cldr_currencies(snapshot: dict[str, Any], *, for_money: bool) -> str:
    raw_symbol = _as_dict(snapshot.get("symbol_to_codes"))
    symbol_to_codes: dict[str, list[str]] = {}
    if raw_symbol:
        symbol_to_codes = {
            str(k): _str_list(v) for k, v in raw_symbol.items() if isinstance(v, list)
        }
    if not symbol_to_codes:
        cldr_inner = _as_dict(
            _as_dict(snapshot.get("cldr_currencies")).get("symbol_to_codes")
        )
        if cldr_inner:
            symbol_to_codes = {
                str(k): _str_list(v)
                for k, v in cldr_inner.items()
                if isinstance(v, list)
            }
    cldr_any = _as_dict(snapshot.get("cldr_currencies"))
    if for_money:
        name_raw = _as_dict(cldr_any.get("name_to_codes_money"))
        name_to_codes: dict[str, list[str]] = (
            {str(k): _str_list(v) for k, v in name_raw.items() if isinstance(v, list)}
            if name_raw
            else {}
        )
        docstring = (
            "Unicode CLDR currency symbol and display-name lookup tables.\n"
            "\n"
            "Source: Unicode CLDR v47 (https://cldr.unicode.org/), English + Spanish\n"
            "currency data (symbols/symbol-alt-narrow and display names).\n"
            "\n"
            "SYMBOL_TO_CODES maps each symbol form to the sorted tuple of ISO 4217\n"
            'codes whose CLDR data uses it ("$" -> the 29 dollar-family codes,\n'
            '"US$" -> ("USD",), "\\u00a5" -> ("CNY", "JPY")). Symbols that equal\n'
            "the code itself, contain whitespace, or are 3-letter uppercase code\n"
            "lookalikes are omitted (CLDR code fallbacks).\n"
            "NAME_TO_CODES maps curated English currency words to their canonical\n"
            'ISO 4217 code ("Dollar" -> ("USD",), "Euro" -> ("EUR",),\n'
            '"Ringgit" -> ("MYR",)).\n'
        )
    else:
        name_raw = _as_dict(cldr_any.get("name_to_codes_currency"))
        name_to_codes = (
            {str(k): _str_list(v) for k, v in name_raw.items() if isinstance(v, list)}
            if name_raw
            else {}
        )
        docstring = (
            "Unicode CLDR currency symbol and display-name lookup tables.\n"
            "\n"
            "Source: Unicode CLDR v47 (https://cldr.unicode.org/), English + Spanish\n"
            "currency data (symbols/symbol-alt-narrow and display names).\n"
            "\n"
            "SYMBOL_TO_CODES maps each symbol form to the sorted tuple of ISO 4217\n"
            'codes whose CLDR data uses it ("$" -> the 29 dollar-family codes,\n'
            '"US$" -> ("USD",), "\\u00a5" -> ("CNY", "JPY")). Symbols that equal\n'
            "the code itself, contain whitespace, are 3-letter uppercase code\n"
            'lookalikes, or equal the generic currency sign "\\u00a4" (U+00A4) are\n'
            "omitted. The generic-sign exclusion is explicit here because XXX is in\n"
            "the full code set; Money excludes XXX entirely, so its derivation never\n"
            "encountered the sign.\n"
            "NAME_TO_CODES maps curated English currency words to their canonical\n"
            'ISO 4217 code ("dollar" -> ("USD",), "euro" -> ("EUR",),\n'
            '"ringgit" -> ("MYR",)).\n'
            "\n"
            "Money divergence (D4): Money's NAME_TO_CODES keys are Title-Case\n"
            '("Dollar"). Currency\'s word grammar folds input to lowercase, so the\n'
            "keys here are lowercase — a deliberate, documented divergence.\n"
        )
    symbol_part = _format_symbol_to_codes(symbol_to_codes)
    name_part = _format_name_to_codes_sorted(name_to_codes)
    assignment = symbol_part + "\n\n" + name_part
    return _emit_module(docstring, assignment)


def _format_currency_codes(codes: list[str]) -> str:
    # Sorted already; emit as frozenset with multiline set literal
    sorted_codes = sorted(codes)
    items = "".join(f'        "{c}",\n' for c in sorted_codes)
    return "CURRENCY_CODES: frozenset[str] = frozenset(\n    {\n" + items + "    }\n)"


def _format_minor_units(minor_units: dict[str, int]) -> str:
    lines: list[str] = []
    lines.append("MINOR_UNITS: dict[str, int] = {")
    for code in sorted(minor_units.keys()):
        lines.append(f'    "{code}": {minor_units[code]},')
    lines.append("}")
    return "\n".join(lines)


def _emit_iso4217(snapshot: dict[str, Any], *, for_money: bool) -> str:
    iso = _as_dict(snapshot.get("iso4217"))
    if for_money:
        codes = [str(c) for c in _as_list(iso.get("currency_codes_money"))]
        minor_raw = _as_dict(iso.get("minor_units"))
        minor_units: dict[str, int] = {str(k): int(v) for k, v in minor_raw.items()}
        codes_part = _format_currency_codes(codes)
        minor_part = _format_minor_units(minor_units)
        assignment = codes_part + "\n\n" + minor_part
        docstring = (
            "ISO 4217 List One snapshot data: currency codes and minor units.\n"
            "\n"
            "Source: ISO 4217 List One "
            "(https://www.six-group.com/en/products-services/\n"
            "        financial-services/data-standards.html), snapshot published "
            "2026-01-01.\n"
            "\n"
            "CURRENCY_CODES holds the 165 codes with a numeric minor-unit exponent;\n"
            'the 13 codes whose CcyMnrUnts is "N.A." (XAG XAU XBA XBB XBC XBD XDR\n'
            "XPD XPT XSU XTS XUA XXX) are excluded: they have no usable minor units.\n"
            "MINOR_UNITS maps each code to its exponent (2 for most, 0 for\n"
            "JPY/KRW/..., 3 for BHD/..., 4 for CLF/UYW).\n"
        )
    else:
        codes = [str(c) for c in _as_list(iso.get("currency_codes_full"))]
        assignment = _format_currency_codes(codes)
        docstring = (
            "ISO 4217 List One snapshot data: currency codes.\n"
            "\n"
            "Source: ISO 4217 Maintenance Agency (SIX Financial Information AG)\n"
            "        List One (https://www.six-group.com/en/products-services/\n"
            "        financial-services/data-standards.html), published 2026-01-01,\n"
            "        as amended by the amendment series through #180.\n"
            "\n"
            "CURRENCY_CODES holds the full List One set of 178 codes, including the\n"
            '13 codes whose CcyMnrUnts is "N.A." (XAG XAU XBA XBB XBC XBD XDR XPD XPT\n'
            "XSU XTS XUA XXX).\n"
            "\n"
            "Money divergence (D2): the Money capability ships only the 165 codes\n"
            "with a numeric minor-unit exponent — it excludes these 13 because\n"
            "amounts need usable minor units. Currency canonicalizes identifiers\n"
            'alone, so a bare "XAU" resolving to "XAU" is correct, and the full set\n'
            "is shipped here.\n"
        )
    return _emit_module(docstring, assignment)


def _modules() -> list[tuple[Path, str]]:
    snap = _load_snapshot()
    return [
        (OUTPUTS[0], _emit_currency_symbols(snap, for_money=False)),
        (OUTPUTS[1], _emit_currency_words(snap, for_money=False)),
        (OUTPUTS[2], _emit_cldr_currencies(snap, for_money=False)),
        (OUTPUTS[3], _emit_iso4217(snap, for_money=False)),
        (OUTPUTS[4], _emit_currency_symbols(snap, for_money=True)),
        (OUTPUTS[5], _emit_currency_words(snap, for_money=True)),
        (OUTPUTS[6], _emit_cldr_currencies(snap, for_money=True)),
        (OUTPUTS[7], _emit_iso4217(snap, for_money=True)),
    ]


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Regenerate Currency/Money data modules."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and exit non-zero if any module drifts",
    )
    args = parser.parse_args()
    modules = _modules()
    if args.check:
        drifted = [
            path
            for path, text in modules
            if not path.exists() or path.read_text(encoding="utf-8") != text
        ]
        if drifted:
            for path in drifted:
                print(
                    f"DRIFT: {path.relative_to(ROOT)} differs from generated output",
                    file=sys.stderr,
                )
            raise SystemExit(1)
        print("all Currency/Money generated data modules are up to date")
        return
    for path, text in modules:
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
