"""Regenerate the UNSPSC codeset membership module from the shared snapshot.

Source: paxman/shared_data/unspsc_snapshot.json
    (UNGM Public/UNSPSC Excel export, fetched 2026-09-30; the UNDP
    v26.0801 XLSX download is access-gated (403), so the snapshot holds
    the live-directory subset until the full 158,448-row codeset can be
    ingested — see the snapshot's ``full_codeset_note``).
Output (1 file, deterministic, sorted):
- paxman/capabilities/UNSPSC/rules/data/unspsc_codeset.py

Step 0 (XLSX -> snapshot, one-time bootstrap, stdlib only): download the
UNGM export (https://www.ungm.org/Public/UNSPSC/Excel), unzip, read the
Code column (C) of xl/worksheets/sheet1.xml resolving shared strings via
xl/sharedStrings.xml, keep fullmatch(r'\\d{8}') codes, synthesize any
pair-prefix family ancestors implied by live classes (flagged in
``synthesized_ancestors``), and write the sorted stems to the snapshot.

Usage:
    uv run python tools/regenerate_unspsc_data.py
    uv run python tools/regenerate_unspsc_data.py --check
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / "paxman" / "shared_data" / "unspsc_snapshot.json"
OUTPUT = (
    ROOT / "paxman" / "capabilities" / "UNSPSC" / "rules" / "data" / "unspsc_codeset.py"
)

_GENERATED_HEADER = (
    "GENERATED by tools/regenerate_unspsc_data.py — do not edit by hand."
)


def _load_snapshot() -> dict[str, object]:
    data: dict[str, object] = json.loads(SNAPSHOT.read_text(encoding="utf-8"))
    return data


def _render_module(version: str, count: int, synth: list[str], stems: list[str]) -> str:
    lines = [
        f'"""{_GENERATED_HEADER}',
        "",
        "UNDP UNSPSC codeset snapshot (live-directory subset).",
        "Source: UNGM Public/UNSPSC Excel export, fetched 2026-09-30.",
        f"Stems: {count} live 8-digit codes.",
        "Coverage: partial — the UNDP v26.0801 XLSX (158,448 items) is",
        "access-gated; this table holds the live-directory subset until the",
        "full codeset can be ingested. Do not cite stem absence as",
        "codeset absence beyond this pinned snapshot.",
    ]
    if synth:
        lines.append(
            f"Synthesized family ancestors ({len(synth)}, flagged in the "
            "snapshot): " + ", ".join(synth) + "."
        )
    lines += [
        "",
        "Regenerate with: uv run python tools/regenerate_unspsc_data.py",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        f'CODESET_VERSION: str = "{version}"',
        "",
        "LIVE_STEMS: frozenset[str] = frozenset(",
        "    {",
    ]
    lines += [f'        "{stem}",' for stem in stems]
    lines += ["    }", ")", ""]
    return "\n".join(lines)


def _modules() -> list[tuple[Path, str]]:
    snap = _load_snapshot()
    version = str(snap["codeset_version"])
    raw_stems = snap["stems"]
    assert isinstance(raw_stems, list)
    stems = sorted(str(s) for s in raw_stems)
    raw_synth = snap.get("synthesized_ancestors", [])
    assert isinstance(raw_synth, list)
    synth = sorted(str(s) for s in raw_synth)
    for stem in stems:
        if len(stem) != 8 or not stem.isascii() or not stem.isdigit():
            raise SystemExit(f"snapshot holds non-8-digit stem: {stem!r}")
    text = _render_module(version, len(stems), synth, stems)
    return [(OUTPUT, text)]


def main() -> None:
    parser = argparse.ArgumentParser(description="Regenerate UNSPSC codeset data.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and exit non-zero if the module drifts",
    )
    args = parser.parse_args()
    modules = _modules()
    if args.check:
        drifted = [
            path
            for path, text in modules
            if not path.exists() or path.read_text(encoding="utf-8") != text
        ]
        if drifted:
            for path in drifted:
                print(
                    f"DRIFT: {path.relative_to(ROOT)} differs from generated output",
                    file=sys.stderr,
                )
            raise SystemExit(1)
        print("UNSPSC codeset data module is up to date")
        return
    for path, text in modules:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
