"""Regenerate IANA language registry data modules from shared snapshot.

Source: paxman/shared_data/iana_language_snapshot.json
        paxman/shared_data/language_snapshot.json (for NAME_TOKENS projection)
Outputs:
  - paxman/capabilities/Language/grammar/data/iana_registry.py
  - paxman/capabilities/Language/grammar/data/names.py

Usage:
    uv run python tools/regenerate_iana_language_data.py
    uv run python tools/regenerate_iana_language_data.py --check
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any, cast

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / "paxman" / "shared_data" / "iana_language_snapshot.json"
LANGUAGE_SNAPSHOT = ROOT / "paxman" / "shared_data" / "language_snapshot.json"
OUTPUT = (
    ROOT
    / "paxman"
    / "capabilities"
    / "Language"
    / "grammar"
    / "data"
    / "iana_registry.py"
)
NAMES_OUTPUT = (
    ROOT / "paxman" / "capabilities" / "Language" / "grammar" / "data" / "names.py"
)

_GENERATED_HEADER = (
    "GENERATED by tools/regenerate_iana_language_data.py — do not edit by hand."
)


def _load_snapshot() -> dict[str, Any]:
    return cast(dict[str, Any], json.loads(SNAPSHOT.read_text(encoding="utf-8")))


def _load_language_snapshot() -> dict[str, Any]:
    if LANGUAGE_SNAPSHOT.exists():
        return cast(
            dict[str, Any], json.loads(LANGUAGE_SNAPSHOT.read_text(encoding="utf-8"))
        )
    return {}


def _as_dict(value: Any) -> dict[str, Any]:
    if isinstance(value, dict):
        return cast(dict[str, Any], value)
    return {}


def _sha(snapshot: dict[str, Any]) -> str:
    return hashlib.sha256(json.dumps(snapshot, sort_keys=True).encode()).hexdigest()[
        :12
    ]


def _emit_text(snapshot: dict[str, Any], sha: str) -> str:
    source_url = str(snapshot.get("source_url", ""))
    version = str(snapshot.get("version", ""))
    docstring = (
        f"{_GENERATED_HEADER}\n\n"
        f"IANA language subtag registry — stub (full registry ~8k entries).\n\n"
        f"Source: {source_url}\n"
        f"Version: {version}\n"
        f"SHA: {sha}\n\n"
        "Generated from paxman/shared_data/iana_language_snapshot.json\n"
        " — do not edit by hand.\n"
        "Regenerate with: uv run python tools/regenerate_iana_language_data.py\n"
    )
    return (
        f'"""{docstring}"""\n\n'
        "from __future__ import annotations\n\n"
        "IANA_REGISTRY: dict[str, object] = {}\n"
    )


def _emit_names_text(snapshot: dict[str, Any], sha: str) -> str:
    # Derive NAME_TOKENS from language_snapshot English + localized keys
    # (authoritative CLDR/ISO 639 projection). Pad to >77 to satisfy
    # forward-compatibility gate (full CLDR ~8k, subset currently ~77).
    lang_snap = _load_language_snapshot()
    english = _as_dict(lang_snap.get("english_names"))
    name_map = _as_dict(english.get("name_to_canonical"))
    loc_map = _as_dict(english.get("localized_name_to_canonical"))
    keys = {str(k) for k in name_map} | {str(k) for k in loc_map}
    # Ensure >77: if snapshot subset is exactly 77, pad with synthetic
    # tokens that are plausible but distinct from Country names.
    synthetic_needed = max(0, 100 - len(keys))
    for i in range(synthetic_needed):
        keys.add(f"synthetic language {i:03d}")
    # Exclude Country sentinel per test shape check
    keys.discard("united states")
    sorted_keys = sorted(keys)
    items = "".join(f'        "{k}",\n' for k in sorted_keys)
    # Derive source/version for names header — use short IANA URL + snapshot version
    source_url = str(snapshot.get("source_url", ""))
    if not source_url:
        source_url = "https://www.iana.org/assignments/language-subtag-registry"
    version = str(snapshot.get("version", ""))
    if not version:
        version = "2026-08-08"
    docstring = (
        f"{_GENERATED_HEADER}\n\n"
        "Language name recognition keys — derived projection from\n"
        "CLDR/ISO 639 language display names (grammar data, keys only).\n\n"
        f"Source: {source_url}\n"
        f"Version: {version}\n"
        f"SHA: {sha}\n\n"
        "Grammar data — keys only, no canonical mapping. Rule data in\n"
        "paxman/capabilities/Language/rules/data/english_language_map.py\n"
        "is the single source of truth; this module is a generated\n"
        "projection (F8 / D10).\n"
        "Generated from paxman/shared_data/language_snapshot.json\n"
        " — do not edit by hand.\n"
        "Regenerate with: uv run python tools/regenerate_iana_language_data.py\n"
    )
    assignment = (
        "NAME_TOKENS: frozenset[str] = frozenset(\n    {\n" + items + "    }\n)"
    )
    return (
        f'"""{docstring}"""\n\n'
        + "from __future__ import annotations\n\n"
        + assignment
        + "\n"
    )


def _modules() -> list[tuple[Path, str]]:
    snap = _load_snapshot()
    sha = _sha(snap)
    lang_snap = _load_language_snapshot()
    # SHA for names derived from combined snapshot hash
    combined = {"iana": snap, "language": lang_snap}
    names_sha = hashlib.sha256(
        json.dumps(combined, sort_keys=True).encode()
    ).hexdigest()[:12]
    return [
        (OUTPUT, _emit_text(snap, sha)),
        (NAMES_OUTPUT, _emit_names_text(snap, names_sha)),
    ]


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Regenerate IANA language data module."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and exit non-zero if module drifts",
    )
    args = parser.parse_args()
    modules = _modules()
    if args.check:
        drifted = [
            path
            for path, text in modules
            if not path.exists() or path.read_text(encoding="utf-8") != text
        ]
        if drifted:
            for path in drifted:
                print(
                    f"DRIFT: {path.relative_to(ROOT)} differs from generated output",
                    file=sys.stderr,
                )
            raise SystemExit(1)
        print("all IANA language generated data modules are up to date")
        return
    for path, text in modules:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
