"""Regenerate BIC country-code lexicon from rule-side authority data.

Source: paxman/capabilities/BIC/rules/iso_9362_ed2022.py (COUNTRY_CODES)
Output: paxman/capabilities/BIC/grammar/data/country_codes.py

The grammar's country-code alternation is a projection of the rule's
authority table — single source of truth (F8 / D10).

Usage:
    uv run python tools/regenerate_bic_data.py
    uv run python tools/regenerate_bic_data.py --check
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "paxman" / "capabilities" / "BIC" / "rules" / "iso_9362_ed2022.py"
OUTPUT = (
    ROOT / "paxman" / "capabilities" / "BIC" / "grammar" / "data" / "country_codes.py"
)

_GENERATED_HEADER = "GENERATED by tools/regenerate_bic_data.py — do not edit by hand."


def _load_rule_codes() -> frozenset[str]:
    # Import authoritative set without relying on file-parse heuristics.
    # Lazy import keeps the module usable even when the generated file is absent.
    from paxman.capabilities.BIC.rules.iso_9362_ed2022 import COUNTRY_CODES

    return COUNTRY_CODES


def _sha(codes: frozenset[str]) -> str:
    payload = json.dumps(sorted(codes), sort_keys=True)
    return hashlib.sha256(payload.encode()).hexdigest()[:12]


def _emit_text(codes: frozenset[str], sha: str) -> str:
    sorted_codes = sorted(codes)
    items = "".join(f'        "{c}",\n' for c in sorted_codes)
    docstring = (
        f"{_GENERATED_HEADER}\n\n"
        "BIC country codes — derived projection from rule authority data.\n\n"
        "Source: paxman/capabilities/BIC/rules/iso_9362_ed2022.py\n"
        "Reference: ISO 9362:2022 Section 5 + ISO 3166-1 alpha-2 plus XK\n"
        "Version: 2022\n"
        f"SHA: {sha}\n\n"
        "Grammar data — keys only, no authority mapping. Rule data in\n"
        "paxman/capabilities/BIC/rules/iso_9362_ed2022.py is the single\n"
        "source of truth; this module is a generated projection.\n"
        "Generated from paxman/capabilities/BIC/rules/iso_9362_ed2022.py\n"
        " — do not edit by hand.\n"
        "Regenerate with: uv run python tools/regenerate_bic_data.py\n"
    )
    assignment = (
        "COUNTRY_CODES: frozenset[str] = frozenset(\n    {\n" + items + "    }\n)"
    )
    return (
        f'"""{docstring}"""\n\n'
        + "from __future__ import annotations\n\n"
        + assignment
        + "\n"
    )


def _modules() -> list[tuple[Path, str]]:
    codes = _load_rule_codes()
    sha = _sha(codes)
    return [(OUTPUT, _emit_text(codes, sha))]


def main() -> None:
    parser = argparse.ArgumentParser(description="Regenerate BIC country-code data.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and exit non-zero if module drifts",
    )
    args = parser.parse_args()
    modules = _modules()
    if args.check:
        drifted = [
            path
            for path, text in modules
            if not path.exists() or path.read_text(encoding="utf-8") != text
        ]
        if drifted:
            for path in drifted:
                print(
                    f"DRIFT: {path.relative_to(ROOT)} differs from generated output",
                    file=sys.stderr,
                )
            raise SystemExit(1)
        print("all BIC generated data modules are up to date")
        return
    for path, text in modules:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
