"""Regenerate IBAN registry data modules from shared snapshot.

Source: paxman/shared_data/iban_registry_snapshot.json
Outputs:
- paxman/capabilities/IBAN/grammar/data/registry.py  (grammar-side, empty-ish)
- paxman/capabilities/IBAN/rules/data/iban_registry.py (authority tables)

Usage:
    uv run python tools/regenerate_iban_registry_data.py
    uv run python tools/regenerate_iban_registry_data.py --check
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any, cast

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / "paxman" / "shared_data" / "iban_registry_snapshot.json"
OUTPUT_GRAMMAR = (
    ROOT / "paxman" / "capabilities" / "IBAN" / "grammar" / "data" / "registry.py"
)
OUTPUT_RULES = (
    ROOT / "paxman" / "capabilities" / "IBAN" / "rules" / "data" / "iban_registry.py"
)

_GENERATED_HEADER = (
    "GENERATED by tools/regenerate_iban_registry_data.py — do not edit by hand."
)


def _load_snapshot() -> dict[str, Any]:
    return cast(dict[str, Any], json.loads(SNAPSHOT.read_text(encoding="utf-8")))


def _sha(snapshot: dict[str, Any]) -> str:
    return hashlib.sha256(json.dumps(snapshot, sort_keys=True).encode()).hexdigest()[
        :12
    ]


def _emit_grammar_text(snapshot: dict[str, Any], sha: str) -> str:
    source_url = str(snapshot.get("source_url", ""))
    version = str(snapshot.get("version", ""))
    count = len(snapshot.get("data", {}))
    docstring = (
        f"{_GENERATED_HEADER}\n\n"
        f"IBAN registry — SWIFT {count}-country rows.\n\n"
        f"Source: {source_url}\n"
        f"Version: {version}\n"
        f"SHA: {sha}\n\n"
        "Generated from paxman/shared_data/iban_registry_snapshot.json\n"
        " — do not edit by hand.\n"
        "Regenerate with: uv run python tools/regenerate_iban_registry_data.py\n"
    )
    data = snapshot.get("data", {})
    # Grammar side keeps minimal registry (country -> length) for parity.
    # Grammar itself does not import this (syntax-only).
    lines = []
    for cc in sorted(data.keys()):
        info = data[cc]
        # Use json.dumps for double-quoted, ruff-compliant strings
        country_json = json.dumps(info["country"])
        row = f'{{"country": {country_json}, "iban_length": {info["iban_length"]}}}'
        lines.append(f'    "{cc}": {row},')
    body = "\n".join(lines)
    return (
        f'"""{docstring}"""\n\n'
        "from __future__ import annotations\n\n"
        f"REGISTRY: dict[str, dict[str, object]] = {{\n{body}\n}}\n"
    )


def _emit_rules_text(snapshot: dict[str, Any], sha: str) -> str:
    source_url = str(snapshot.get("source_url", ""))
    version = str(snapshot.get("version", ""))
    count = len(snapshot.get("data", {}))
    docstring = (
        f"{_GENERATED_HEADER}\n\n"
        f"IBAN registry — SWIFT {count}-country authority tables.\n\n"
        f"Source: {source_url}\n"
        f"Version: {version}\n"
        f"SHA: {sha}\n\n"
        "Generated from paxman/shared_data/iban_registry_snapshot.json\n"
        " — do not edit by hand.\n"
        "Regenerate with: uv run python tools/regenerate_iban_registry_data.py\n"
    )
    data = snapshot.get("data", {})
    # Build frozenset and length dict
    codes = sorted(data.keys())
    lengths = {cc: data[cc]["iban_length"] for cc in codes}
    codes_repr = ",\n        ".join(f'"{c}"' for c in codes)
    # format lengths dict
    length_lines = ",\n    ".join(f'"{cc}": {lengths[cc]}' for cc in codes)
    rules_header = (
        f"REGISTERED_IBAN_COUNTRY_CODES: frozenset[str] = frozenset("
        f"\n    {{\n        {codes_repr},\n    }}\n)\n\n"
    )
    return (
        f'"""{docstring}"""\n\n'
        "from __future__ import annotations\n\n"
        f"{rules_header}"
        f"IBAN_LENGTHS: dict[str, int] = {{\n    {length_lines},\n}}\n"
    )


def _modules() -> list[tuple[Path, str]]:
    snap = _load_snapshot()
    sha = _sha(snap)
    return [
        (OUTPUT_GRAMMAR, _emit_grammar_text(snap, sha)),
        (OUTPUT_RULES, _emit_rules_text(snap, sha)),
    ]


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Regenerate IBAN registry data modules."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and exit non-zero if module drifts",
    )
    args = parser.parse_args()
    modules = _modules()
    if args.check:
        drifted = [
            path
            for path, text in modules
            if not path.exists() or path.read_text(encoding="utf-8") != text
        ]
        if drifted:
            for path in drifted:
                print(
                    f"DRIFT: {path.relative_to(ROOT)} differs from generated output",
                    file=sys.stderr,
                )
            raise SystemExit(1)
        print("all IBAN registry generated data modules are up to date")
        return
    for path, text in modules:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
