"""Regenerate Language data modules from shared snapshot.

Source: paxman/shared_data/language_snapshot.json
 (IANA Language Subtag Registry 2026-08-08 + ISO 639 family + BCP47 RFC 5646).
Outputs (5 files, deterministic, sorted ordering):
- paxman/capabilities/Language/grammar/data/grandfathered_tags.py
- paxman/capabilities/Language/grammar/data/english_names.py
- paxman/capabilities/Language/grammar/data/localized_names.py
- paxman/capabilities/Language/rules/data/iana_grandfathered.py
- paxman/capabilities/Language/rules/data/english_language_map.py

Regeneration preserves import-linter isolation: grammar/data never imports
from rules/data; each generated file is standalone with literal frozenset/dict.
Sibling imports remain banned (M8).

Usage:
    uv run python tools/regenerate_language_data.py
    uv run python tools/regenerate_language_data.py --check
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, cast

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / "paxman" / "shared_data" / "language_snapshot.json"

_GENERATED_HEADER = (
    "GENERATED by tools/regenerate_language_data.py — do not edit by hand."
)

OUTPUTS = [
    ROOT
    / "paxman"
    / "capabilities"
    / "Language"
    / "grammar"
    / "data"
    / "grandfathered_tags.py",
    ROOT
    / "paxman"
    / "capabilities"
    / "Language"
    / "grammar"
    / "data"
    / "english_names.py",
    ROOT
    / "paxman"
    / "capabilities"
    / "Language"
    / "grammar"
    / "data"
    / "localized_names.py",
    ROOT
    / "paxman"
    / "capabilities"
    / "Language"
    / "rules"
    / "data"
    / "iana_grandfathered.py",
    ROOT
    / "paxman"
    / "capabilities"
    / "Language"
    / "rules"
    / "data"
    / "english_language_map.py",
]


def _emit_module(docstring: str, assignment: str) -> str:
    return (
        '"""'
        + _GENERATED_HEADER
        + "\n\n"
        + docstring
        + '"""\n\nfrom __future__ import annotations\n\n'
        + assignment
        + "\n"
    )


def _load_snapshot() -> dict[str, Any]:
    return cast(dict[str, Any], json.loads(SNAPSHOT.read_text(encoding="utf-8")))


def _as_dict(value: Any) -> dict[str, Any]:
    if isinstance(value, dict):
        return cast(dict[str, Any], value)
    return {}


def _as_list(value: Any) -> list[Any]:
    if isinstance(value, list):
        return cast(list[Any], value)
    return []


def _emit_grammar_grandfathered(snapshot: dict[str, Any]) -> str:
    grandfathered = _as_dict(snapshot.get("grandfathered"))
    tags = [str(t) for t in _as_list(grandfathered.get("tags"))]
    tags_sorted = sorted(tags)
    items = "".join(f'        "{t}",\n' for t in tags_sorted)
    assignment = (
        "GRANDFATHERED_TAGS: frozenset[str] = frozenset(\n    {\n" + items + "    }\n)"
    )
    docstring = (
        "IANA Language Subtag Registry — Type: grandfathered (grammar data).\n"
        "\n"
        "Source: IANA Language Subtag Registry\n"
        "Reference: https://www.iana.org/assignments/language-subtag-registry/"
        "language-subtag-registry\n"
        "File-Date: 2026-08-08\n"
        "Type: grandfathered 27 entries (26 authority + i-cherokee test "
        "vector), all Deprecated.\n"
        "\n"
        "Separation: grammar data — keys only, no Preferred-Value mapping.\n"
        "Generated from paxman/shared_data/language_snapshot.json — do not "
        "edit by hand.\n"
        "Regenerate with: uv run python tools/regenerate_language_data.py\n"
    )
    return _emit_module(docstring, assignment)


def _emit_grammar_english_names(snapshot: dict[str, Any]) -> str:
    english = _as_dict(snapshot.get("english_names"))
    name_map = _as_dict(english.get("name_to_canonical"))
    keys = sorted(str(k) for k in name_map)
    items = "".join(f'        "{k}",\n' for k in keys)
    assignment = (
        "ENGLISH_LANGUAGE_KEYS: frozenset[str] = frozenset(\n    {\n"
        + items
        + "    }\n)"
    )
    docstring = (
        "English language name recognition keys (grammar data).\n"
        "\n"
        "Source: ISO 639 English Description + IANA Registry\n"
        "Reference: https://www.iso.org/standard/22109.html\n"
        "Keys are normalize_name() output (lower, accent-stripped, "
        "space-collapsed).\n"
        "\n"
        "Completeness: curatorial subset (60 entries from snapshot). The full\n"
        "IANA Language Subtag Registry Description set (7,900+) and CLDR root\n"
        "are not yet materialized. Names outside this subset are MISSING\n"
        "(grammar emits no match), not INVALID — no false negative under the\n"
        "current completeness contract. Full IANA Description coverage is\n"
        "tracked as follow-up work; snapshot _meta documents provenance.\n"
        "\n"
        "Generated from paxman/shared_data/language_snapshot.json — do not "
        "edit by hand.\n"
        "Regenerate with: uv run python tools/regenerate_language_data.py\n"
    )
    return _emit_module(docstring, assignment)


def _emit_grammar_localized_names(snapshot: dict[str, Any]) -> str:
    english = _as_dict(snapshot.get("english_names"))
    loc_map = _as_dict(english.get("localized_name_to_canonical"))
    keys = sorted(str(k) for k in loc_map)
    items = "".join(f'        "{k}",\n' for k in keys)
    assignment = (
        "LOCALIZED_LANGUAGE_KEYS: frozenset[str] = frozenset(\n    {\n"
        + items
        + "    }\n)"
    )
    docstring = (
        "Localized (CLDR) language name recognition keys (grammar data).\n"
        "\n"
        "Source: CLDR language display names (subset: en/fr/de/es latn)\n"
        "Reference: https://www.unicode.org/cldr/charts/46/summary/root.html\n"
        "Keys are normalize_name() output (lower, accent-stripped, "
        "space-collapsed).\n"
        "\n"
        "Completeness: curatorial subset (24 entries from snapshot). Full\n"
        "CLDR v46 locale coverage is not yet generated. In-subset localized\n"
        "names without include_localized are INVALID (grammar recognizes,\n"
        "engine drops the CLDR rule via requires_features); out-of-subset\n"
        "names are MISSING (grammar emits no match), not INVALID. Snapshot\n"
        "_meta documents unsupported provenance.\n"
        "\n"
        "Generated from paxman/shared_data/language_snapshot.json — do not "
        "edit by hand.\n"
        "Regenerate with: uv run python tools/regenerate_language_data.py\n"
    )
    return _emit_module(docstring, assignment)


def _emit_rules_grandfathered(snapshot: dict[str, Any]) -> str:
    grandfathered = _as_dict(snapshot.get("grandfathered"))
    tags = [str(t) for t in _as_list(grandfathered.get("tags"))]
    tags_sorted = sorted(tags)
    preferred_raw = _as_dict(grandfathered.get("preferred"))
    preferred: dict[str, str] = {str(k): str(v) for k, v in preferred_raw.items()}

    tags_items = "".join(f'        "{t}",\n' for t in tags_sorted)
    tags_assignment = (
        "GRANDFATHERED_TAGS: frozenset[str] = frozenset(\n    {\n"
        + tags_items
        + "    }\n)"
    )

    pref_lines: list[str] = []
    pref_lines.append("GRANDFATHERED_PREFERRED: dict[str, str] = {")
    for k in sorted(preferred.keys()):
        pref_lines.append(f'    "{k}": "{preferred[k]}",')
    pref_lines.append("}")
    pref_assignment = "\n".join(pref_lines)

    assignment = tags_assignment + "\n\n" + pref_assignment
    docstring = (
        "IANA Language Subtag Registry — Type: grandfathered.\n"
        "\n"
        "Source: IANA Language Subtag Registry\n"
        "Reference: https://www.iana.org/assignments/language-subtag-registry/"
        "language-subtag-registry\n"
        "File-Date: 2026-08-08\n"
        "Type: grandfathered 27 entries (26 authority + i-cherokee test "
        "vector), all Deprecated.\n"
        "\n"
        "Separation: authority-backed tables serving rules only.\n"
        "Generated from paxman/shared_data/language_snapshot.json — do not "
        "edit by hand.\n"
        "Regenerate with: uv run python tools/regenerate_language_data.py\n"
    )
    return _emit_module(docstring, assignment)


def _emit_rules_english_map(snapshot: dict[str, Any]) -> str:
    english = _as_dict(snapshot.get("english_names"))
    name_raw = _as_dict(english.get("name_to_canonical"))
    loc_raw = _as_dict(english.get("localized_name_to_canonical"))
    name_map: dict[str, str] = {str(k): str(v) for k, v in name_raw.items()}
    loc_map: dict[str, str] = {str(k): str(v) for k, v in loc_raw.items()}

    name_lines: list[str] = []
    name_lines.append("NAME_TO_CANONICAL: dict[str, str] = {")
    for k in sorted(name_map):
        name_lines.append(f'    "{k}": "{name_map[k]}",')
    name_lines.append("}")
    name_part = "\n".join(name_lines)

    loc_lines: list[str] = []
    loc_lines.append("LOCALIZED_NAME_TO_CANONICAL: dict[str, str] = {")
    for k in sorted(loc_map):
        loc_lines.append(f'    "{k}": "{loc_map[k]}",')
    loc_lines.append("}")
    loc_part = "\n".join(loc_lines)

    cldr_part = "CLDR_MAP: dict[str, str] = LOCALIZED_NAME_TO_CANONICAL"

    assignment = name_part + "\n\n" + loc_part + "\n\n" + cldr_part
    docstring = (
        "Language display name → canonical code mappings.\n"
        "\n"
        "Source: ISO 639 English Description + IANA Registry\n"
        "Reference: https://www.iso.org/standard/22109.html\n"
        "CLDR Source: https://www.unicode.org/cldr/charts/46/summary/root.html\n"
        "\n"
        "Keys are normalize_name() output (lower, accent-stripped, "
        "space-collapsed).\n"
        "Values are lower canonical language codes (alpha-2 when available, "
        "else alpha-3 Term).\n"
        "\n"
        "Completeness: English names are a curatorial subset (60 entries);\n"
        "localized names are a CLDR subset (24 entries, en/fr/de/es). The\n"
        "full IANA Registry Description set (7,900+) and CLDR v46 root locale\n"
        "are not yet materialized. Names outside these subsets are MISSING\n"
        "(grammar emits no match) rather than INVALID, avoiding false\n"
        "negatives under the current completeness contract. Full coverage\n"
        "will be generated from the IANA Registry file and CLDR root data;\n"
        "until then unsupported provenance is documented in the snapshot\n"
        "_meta and capability docstring.\n"
        "\n"
        "Separation: authority-backed tables serving rules only.\n"
        "Generated from paxman/shared_data/language_snapshot.json — do not "
        "edit by hand.\n"
        "Regenerate with: uv run python tools/regenerate_language_data.py\n"
    )
    return _emit_module(docstring, assignment)


def _modules() -> list[tuple[Path, str]]:
    snap = _load_snapshot()
    return [
        (OUTPUTS[0], _emit_grammar_grandfathered(snap)),
        (OUTPUTS[1], _emit_grammar_english_names(snap)),
        (OUTPUTS[2], _emit_grammar_localized_names(snap)),
        (OUTPUTS[3], _emit_rules_grandfathered(snap)),
        (OUTPUTS[4], _emit_rules_english_map(snap)),
    ]


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Regenerate Language data modules from shared snapshot."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and exit non-zero if any module drifts",
    )
    args = parser.parse_args()
    modules = _modules()
    if args.check:
        drifted = [
            path
            for path, text in modules
            if not path.exists() or path.read_text(encoding="utf-8") != text
        ]
        if drifted:
            for path in drifted:
                print(
                    f"DRIFT: {path.relative_to(ROOT)} differs from generated output",
                    file=sys.stderr,
                )
            raise SystemExit(1)
        print("all Language generated data modules are up to date")
        return
    for path, text in modules:
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
