"""Regenerate IBAN registry data module from shared snapshot.

Source: paxman/shared_data/iban_registry_snapshot.json
Output: paxman/capabilities/IBAN/grammar/data/registry.py

Usage:
    uv run python tools/regenerate_iban_registry_data.py
    uv run python tools/regenerate_iban_registry_data.py --check
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any, cast

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / "paxman" / "shared_data" / "iban_registry_snapshot.json"
OUTPUT = ROOT / "paxman" / "capabilities" / "IBAN" / "grammar" / "data" / "registry.py"

_GENERATED_HEADER = (
    "GENERATED by tools/regenerate_iban_registry_data.py — do not edit by hand."
)


def _load_snapshot() -> dict[str, Any]:
    return cast(dict[str, Any], json.loads(SNAPSHOT.read_text(encoding="utf-8")))


def _sha(snapshot: dict[str, Any]) -> str:
    return hashlib.sha256(json.dumps(snapshot, sort_keys=True).encode()).hexdigest()[
        :12
    ]


def _emit_text(snapshot: dict[str, Any], sha: str) -> str:
    source_url = str(snapshot.get("source_url", ""))
    version = str(snapshot.get("version", ""))
    docstring = (
        f"{_GENERATED_HEADER}\n\n"
        f"IBAN registry — SWIFT 90-country rows (stub).\n\n"
        f"Source: {source_url}\n"
        f"Version: {version}\n"
        f"SHA: {sha}\n\n"
        "Generated from paxman/shared_data/iban_registry_snapshot.json\n"
        " — do not edit by hand.\n"
        "Regenerate with: uv run python tools/regenerate_iban_registry_data.py\n"
    )
    return (
        f'"""{docstring}"""\n\n'
        "from __future__ import annotations\n\n"
        "REGISTRY: dict[str, object] = {}\n"
    )


def _modules() -> list[tuple[Path, str]]:
    snap = _load_snapshot()
    sha = _sha(snap)
    return [(OUTPUT, _emit_text(snap, sha))]


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Regenerate IBAN registry data module."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and exit non-zero if module drifts",
    )
    args = parser.parse_args()
    modules = _modules()
    if args.check:
        drifted = [
            path
            for path, text in modules
            if not path.exists() or path.read_text(encoding="utf-8") != text
        ]
        if drifted:
            for path in drifted:
                print(
                    f"DRIFT: {path.relative_to(ROOT)} differs from generated output",
                    file=sys.stderr,
                )
            raise SystemExit(1)
        print("all IBAN registry generated data modules are up to date")
        return
    for path, text in modules:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
