"""Regenerate paxman/core/grammar/data/unicode_ranges.py.

Usage:
    uv run python tools/regenerate_unicode_property_data.py
    uv run python tools/regenerate_unicode_property_data.py --check

Reads the committed Unicode property snapshot JSON and emits the data module.
Run manually when the snapshot is refreshed. Standard library only.
No network access — snapshot is vendored.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
SNAPSHOT = _REPO_ROOT / "paxman" / "shared_data" / "unicode_snapshot.json"
OUTPUT = _REPO_ROOT / "paxman" / "core" / "grammar" / "data" / "unicode_ranges.py"

_GENERATED_HEADER = (
    "GENERATED by tools/regenerate_unicode_property_data.py — do not edit by hand."
)


def _load_snapshot() -> dict[str, object]:
    text = SNAPSHOT.read_text(encoding="utf-8")
    data = json.loads(text)
    if not isinstance(data, dict):
        raise SystemExit("unicode_snapshot.json: expected object")
    return data  # type: ignore[return-value]


def _parse_ranges(raw: object, key: str) -> list[tuple[int, int]]:
    if not isinstance(raw, list):
        raise SystemExit(f"unicode_snapshot.json: {key} must be a list")
    ranges: list[tuple[int, int]] = []
    for idx, item in enumerate(raw):
        if not isinstance(item, list) or len(item) != 2:
            msg = f"unicode_snapshot.json: {key}[{idx}] must be [start, end]"
            raise SystemExit(msg)
        start, end = item
        if not isinstance(start, int) or not isinstance(end, int):
            msg = f"unicode_snapshot.json: {key}[{idx}] must be int pair"
            raise SystemExit(msg)
        if start > end:
            msg = f"unicode_snapshot.json: {key}[{idx}] start > end"
            raise SystemExit(msg)
        if start < 0 or end > 0x10FFFF:
            msg = f"unicode_snapshot.json: {key}[{idx}] out of Unicode range"
            raise SystemExit(msg)
        ranges.append((start, end))
    # deterministic: sorted, non-overlapping check
    ranges.sort()
    for i in range(1, len(ranges)):
        prev_end = ranges[i - 1][1]
        curr_start = ranges[i][0]
        if curr_start <= prev_end:
            msg = (
                f"unicode_snapshot.json: {key} ranges overlap "
                f"or not sorted at index {i}"
            )
            raise SystemExit(msg)
    return ranges


def _format_ranges(ranges: list[tuple[int, int]]) -> str:
    if not ranges:
        return "()"
    lines = [f"    (0x{start:04X}, 0x{end:04X})," for start, end in ranges]
    return "(\n" + "\n".join(lines) + "\n)"


def _render() -> str:
    data = _load_snapshot()
    unicode_version = data.get("unicode_version")
    source_url = data.get("source_url")
    if not isinstance(unicode_version, str) or not unicode_version:
        raise SystemExit("unicode_snapshot.json: missing unicode_version")
    if not isinstance(source_url, str) or not source_url:
        raise SystemExit("unicode_snapshot.json: missing source_url")

    sc_ranges = _parse_ranges(data.get("sc_ranges"), "sc_ranges")
    han_ranges = _parse_ranges(data.get("han_ranges"), "han_ranges")

    doc = (
        f'"""{_GENERATED_HEADER}\n'
        "\n"
        f"Source: {source_url}\n"
        f"Unicode version: {unicode_version}\n"
        '"""\n'
        "\n"
        "from __future__ import annotations\n"
        "\n"
        f'UNICODE_VERSION: str = "{unicode_version}"\n'
        f'SOURCE_URL: str = "{source_url}"\n'
        "\n"
        f"SC_RANGES: tuple[tuple[int, int], ...] = {_format_ranges(sc_ranges)}\n"
        "\n"
        f"HAN_RANGES: tuple[tuple[int, int], ...] = {_format_ranges(han_ranges)}\n"
    )
    if "output_format" in doc:
        raise RuntimeError("generated module must not contain 'output_format'")
    return doc


def main() -> None:
    parser = argparse.ArgumentParser(description="Regenerate Unicode property ranges.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and exit non-zero if drift",
    )
    args = parser.parse_args()
    rendered = _render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            rel = OUTPUT.relative_to(_REPO_ROOT)
            print(
                f"DRIFT: {rel} differs from generated output",
                file=sys.stderr,
            )
            raise SystemExit(1)
        print("all Unicode property generated data modules are up to date")
        return
    OUTPUT.write_text(rendered, encoding="utf-8")
    data = _load_snapshot()
    sc_len = len(_parse_ranges(data.get("sc_ranges"), "sc_ranges"))
    han_len = len(_parse_ranges(data.get("han_ranges"), "han_ranges"))
    rel = OUTPUT.relative_to(_REPO_ROOT)
    print(f"wrote {rel}: {sc_len} Sc ranges, {han_len} Han ranges")


if __name__ == "__main__":
    main()
